name: qaul_ui
description: qaul.net Internet Independent Wireless Mesh Communication App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0-beta+6

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ********
  # UI Dependencies
  # ********
  font_awesome_flutter: ^10.1.0
  # Responsive UI Support => App Wrapper
  responsive_framework: ^0.2.0
  # Dynamic Theme Control => dark, light mode & so on
  adaptive_theme: ^3.0.0
  # SVG-support
  flutter_svg: ^0.23.0+1
  # Notification bubbles on icons
  badges: ^2.0.1
  # Dynamic Network View
  # flame: ^1.0.0
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: 69214827a0edb563468951256eccecab408f89df
      path: packages/flame
  flame_forge2d: ^0.11.0
  open_simplex_2: ^0.2.1


  flutter_markdown: ^0.6.8


  bubble: ^1.2.1
  flutter_chat_ui: ^1.5.1

  ## *******
  ## Desktop dependencies
  ## *******
# TODO: Reinstate once package is fixed. Plugin broke against new Flutter version 2.8
#  bitsdojo_window: ^0.1.1+1
  # Windows-native Widgets
  fluent_ui: ^3.12.0
  # MacOS-native Widgets
  macos_ui: ^0.10.0+1

  # *******
  # Business Logic Dependencies
  # *******
  collection: ^1.15.0
  equatable: ^2.0.3
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^1.0.4
  logging: ^1.0.2

  uuid: ^3.0.5

  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intersperse: ^2.0.0
  intl: ^0.17.0
  meta: ^1.7.0
  uni_links: ^0.5.1

  archive: ^3.1.8
  filesize: ^2.0.1
  path_provider: ^2.0.8
  neat_periodic_task: ^2.0.0
  shared_preferences: ^2.0.12

  device_info_plus: ^3.2.4
  package_info_plus: ^1.3.0

  mailto: ^2.0.0
  url_launcher: ^6.0.18
  flutter_email_sender: ^5.0.2

  # *******
  # Local Dependencies
  # *******
  local_notifications:
    path: packages/local_notifications
  qaul_rpc:
    path: packages/qaul_rpc
  utils:
    path: packages/utils

  cupertino_icons: ^1.0.2

dependency_overrides:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      ref: 69214827a0edb563468951256eccecab408f89df
      path: packages/flame

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  hive_generator: ^1.1.1
  build_runner: ^2.1.4

  fast_base58: ^0.2.1

  flutter_launcher_icons: "^0.9.2"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/logo/icon_ios.png"

  android: true
  image_path_android: "assets/logo/icon_android.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  assets:
    - assets/icons/
    - assets/license/
    - assets/logo/
