[package]
name = "qaul_info"
edition = "2021"
description = "qaul routing-info protocol for libp2p"
version = "1.0.0"
authors = ["qaul community <contact@qaul.net>"]
license = "AGPL"

[dependencies]
libp2p = { version = "0.53.2", features = ["async-std", "macros", "floodsub", "identify", "mdns", "noise", "ping", "tcp", "yamux", "quic", "websocket", "dns", "macros"] }
cuckoofilter = "0.5.0"
fnv = "1.0.7"
futures = "0.3.30"
log = "0.4.21"
rand = "0.8.5"
smallvec = "1.13.2"
asynchronous-codec = "0.7"
bytes = "1.6"
unsigned-varint = "0.8"

# internal references
varint_prefixed_codec = { path = "../varint_prefixed_codec" }
