[package]
name = "qaul_info"
edition = "2021"
description = "qaul routing-info protocol for libp2p"
version = "0.1.0"
authors = ["qaul community <contact@qaul.net>"]
license = "AGPL"

[dependencies]
libp2p = { version = "0.52.0", features = ["async-std", "macros", "floodsub", "identify", "mdns", "noise", "ping", "tcp", "yamux", "websocket", "dns", "macros"] }
cuckoofilter = "0.5.0"
fnv = "1.0"
futures = "0.3.21"
log = "0.4"
rand = "0.8.4"
smallvec = "1.8.0"
