jobs:
  - verify-version-rust:
      filters:
        tags:
          only: /^v\d+\.\d+\.\d+(\+\d)*-rust$/
        branches:
          ignore: /.*/
  - build-libqaul-linux:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /^v\d+\.\d+\.\d+(\+\d)*-rust$/
        branches:
          ignore: /.*/
  - build-libqaul-android:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /^v\d+\.\d+\.\d+(\+\d)*-rust$/
        branches:
          ignore: /.*/
  - build-libqaul-ios:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /^v\d+\.\d+\.\d+(\+\d)*-rust$/
        branches:
          ignore: /.*/
  - build-libqaul-macos:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /^v\d+\.\d+\.\d+(\+\d)*-rust$/
        branches:
          ignore: /.*/
  - build-libqaul-windows:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /^v\d+\.\d+\.\d+(\+\d)*-rust$/
        branches:
          ignore: /.*/
  - publish-rust-github-release:
      requires:
        - build-libqaul-linux
        - build-libqaul-android
        - build-libqaul-ios
        - build-libqaul-macos
        - build-libqaul-windows
      filters:
        tags:
          only: /^v\d+\.\d+\.\d+(\+\d)*-rust$/
        branches:
          ignore: /.*/
