[package]
name = "qaul_messaging"
edition = "2018"
description = "qaul messaging protocol for libp2p"
version = "0.1.0"
authors = ["qaul community <contact@qaul.net>"]
license = "AGPL"

[dependencies]
libp2p = { git = "https://github.com/qaul/rust-libp2p.git", branch = "ios-build-fix", features = ["full"] }
cuckoofilter = "0.5.0"
fnv = "1.0"
futures = "0.3.1"
log = "0.4"
rand = "0.8.4"
smallvec = "1.6.1"
