[package]
name = "libqaul"
version = "2.0.0-beta.17"
authors = ["qaul community <contact@qaul.net>"]
edition = "2021"
license = "AGPL"

[lib]
name = "libqaul"
crate-type = ["cdylib", "staticlib", "rlib"]

[features]
default = []

[dependencies]
libp2p = { version = "0.52.4", features = ["async-std", "macros", "floodsub", "identify", "mdns", "noise", "ping", "tcp", "yamux", "quic", "websocket", "dns", "macros"] }
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.29"
serde = {version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
once_cell = "1.18.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"
simplelog = "0.12.1"
multi_log = "0.1.2"
filetime = "0.2.22"
bincode = "1.3.3"
config = "0.13.4"
lazy_static = "1.4.0"
toml = "0.8.8"
base64 ="0.21.5"
state = "0.6.0"
humantime = "2.1.0"
tracing = "0.1.40"
void = "1.0.2"
wasm-timer = "0.2.5"
rand = "0.8.5"
prost = "0.12.3"
libc = "0.2.150"
crossbeam-channel = "0.5.8"
bs58 = "0.5.0"
futures-ticker = "0.0.3"
jni = "0.21.1"
serde_yaml = "0.9.27"
sled = "0.34.7"
uuid = { version = "1.6.1", features = ["v4"] }
ed25519-dalek = "2.1.0"
x25519-dalek = "2.0.0"
curve25519-dalek = "4.1.1"
sha2 = "0.10.8"
noise-protocol = { git = "https://github.com/qaul/noise-rust.git", branch = "libqaul/noise-rust-crypto-v0.6.2" }
noise-rust-crypto = { git = "https://github.com/qaul/noise-rust.git", branch = "libqaul/noise-rust-crypto-v0.6.2", features = ["use-x25519", "use-chacha20poly1305", "use-sha2"] }
crc = "3.0.1"
fs_extra = "1.3.0"
semver = "1.0.20"

# only for desktop platforms: Linux, Mac, Windows
directories = "5.0.1"

# internal references
qaul_info = { path = "../libp2p_modules/qaul_info" }
qaul_messaging = { path = "../libp2p_modules/qaul_messaging" }

[build-dependencies]
prost-build = "0.12.3"

# special setting for android
[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.3"
