name: qaul
version: 0.1.0
summary: Qaul
description: Internet Independent Wireless Mesh Communication

confinement: strict
base: core18
grade: stable

slots:
  dbus-qaul:
    interface: dbus
    bus: session
    name: net.qaul.qaul

apps:
  qaul:
    command: qaul
    extensions: [ flutter-stable ]
    plugs:
      - network
    slots:
      - dbus-qaul

parts:
  qaul:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
