name: qaul
version: 2.0.0-beta.11
summary: qaul - Internet Independent Wireless Mesh Communication App
description: Communicate directly from device to device via your local wifi network, or via the shared wifi network of your phone. Mesh local clouds together via manually added static nodes. Use this peer to peer communication method to communicate internet independently and completely off-the-grid.

confinement: strict
base: core18
grade: stable

slots:
  dbus-qaul:
    interface: dbus
    bus: session
    name: net.qaul.qaul

apps:
  qaul:
    command: qaul
    extensions: [ flutter-stable ]
    plugs:
      - home
      - network
    slots:
      - dbus-qaul

parts:
  qaul:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
