name: qaul
version: 2.0.0-beta.12
summary: qaul - Internet Independent Wireless Mesh Communication App
description: Communicate directly from device to device via your local wifi network, or via the shared wifi network of your phone. Mesh local clouds together via manually added static nodes. Use this peer to peer communication method to communicate internet independently and completely off-the-grid.

confinement: strict
base: core18
grade: stable

slots:
  dbus-qaul:
    interface: dbus
    bus: session
    name: net.qaul.qaul

apps:
  qaul:
    command: qaul
    extensions: [ flutter-stable ]
    plugs:
      - home
      - mount-observe
      - network
      - network-control
      - process-control
      - system-observe

    slots:
      - dbus-qaul

parts:
  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  libqaul:
    plugin: nil
    source: https://github.com/qaul/qaul.net.git
    after: [ rust-deps ]
    build-packages:
      - protobuf-compiler
      - libc-bin
    stage-packages:
      - libc-bin
    override-build: |
      export PATH="$HOME/.cargo/bin:$PATH"
      cargo --version

      cd rust/libqaul || exit 1
      
      rm build.rs
      cargo build --release
      
      cd ..

      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/lib
      cp target/release/liblibqaul.so $SNAPCRAFT_PART_INSTALL/bin/lib

  qaul:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    override-pull: |
      snapcraftctl pull
      flutter clean
    override-build: |
      BEFORE="_lib = DynamicLibrary.open('../rust/target/\$mode/liblibqaul.so');"
      AFTER="_lib = DynamicLibrary.open('\${Platform.environment['SNAP']}/bin/lib/liblibqaul.so');"
      sed -i -e "s|$BEFORE|$AFTER|g" packages/qaul_rpc/lib/src/libqaul/ffi.dart
      
      snapcraftctl build

  # zenity: is a File Picker dependency (https://github.com/miguelpruivo/flutter_file_picker)
  assets-and-dependencies:
    plugin: nil
    stage-packages:
      - zenity
      - dmz-cursor-theme
      - fonts-dejavu
      - fonts-freefont-ttf
      - fonts-ubuntu

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons

environment:
  LD_LIBRARY_PATH: ${SNAP_LIBRARY_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/bin/lib:/var/lib/snapd/snap/core18