when: << pipeline.parameters.run-flutter-tagged-workflow >>
jobs:
  - verify-version-flutter:
      filters:
        tags:
          only: /.*/
  - test-flutter:
      requires:
        - verify-version-flutter
      filters:
        tags:
          only: /.*/
  - analyze-flutter:
      requires:
        - verify-version-flutter
      filters:
        tags:
          only: /.*/
  - build-and-deploy-flutter-android:
      requires:
        - test-flutter
        - analyze-flutter
      filters:
        tags:
          only: /.*/
  - build-and-deploy-flutter-ios:
      requires:
        - test-flutter
        - analyze-flutter
      filters:
        tags:
          only: /.*/
  - build-flutter-macos:
      requires:
        - test-flutter
        - analyze-flutter
      filters:
        tags:
          only: /.*/
  - build-flutter-windows:
      requires:
        - test-flutter
        - analyze-flutter
      filters:
        tags:
          only: /.*/
  - build-flutter-linux:
      requires:
        - test-flutter
        - analyze-flutter
      filters:
        tags:
          only: /.*/
  - publish-flutter-github-release:
      requires:
        - build-and-deploy-flutter-android
        - build-and-deploy-flutter-ios
        - build-flutter-macos
        - build-flutter-windows
        - build-flutter-linux
      filters:
        tags:
          only: /.*/
