when:
  or:
    - << pipeline.parameters.run-rust-tagged-workflow >>
    - << pipeline.parameters.run-rust-linux-tagged-workflow >>
jobs:
  - verify-version-rust: { "filters": { "tags": { "only": "/.*/" } } }
  - build-libqaul-linux:
      {
        "requires": [ "verify-version-rust" ],
        "filters": { "tags": { "only": "/.*/" } },
      }
  - build-libqaul-arm-linux:
      {
        "requires": [ "verify-version-rust" ],
        "filters": { "tags": { "only": "/.*/" } },
      }
  - build-qauld-linux:
      {
        "requires": [ "verify-version-rust" ],
        "filters": { "tags": { "only": "/.*/" } },
      }
  - build-qauld-arm-linux:
      {
        "requires": [ "verify-version-rust" ],
        "filters": { "tags": { "only": "/.*/" } },
      }
  - generate-sbom: {
    'requires':
      [
        "build-libqaul-linux",
        "build-libqaul-arm-linux",
        "build-qauld-linux",
        "build-qauld-arm-linux",
      ],
    'filters': { 'tags': { 'only': '/.*/' } }
  }
  - publish-rust-github-release: { 'requires': [ 'generate-sbom' ], 'filters': { 'tags': { 'only': '/.*/' } } }
