when:
  or:
    - << pipeline.parameters.run-rust-tagged-workflow >>
    - << pipeline.parameters.run-rust-ios-tagged-workflow >>
jobs:
  - verify-version-rust: { 'filters': { 'tags': { 'only': '/.*/' } } }
  - build-libqaul-ios: { 'requires': [ 'verify-version-rust' ], 'filters': { 'tags': { 'only': '/.*/' } } }
  - generate-sbom: { 'requires': [ 'build-libqaul-ios' ], 'filters': { 'tags': { 'only': '/.*/' } } }
  - publish-rust-github-release: { 'requires': [ 'generate-sbom' ], 'filters': { 'tags': { 'only': '/.*/' } } }
