when: << pipeline.parameters.run-rust-tagged-workflow >>
jobs:
  - verify-version-rust:
      filters:
        tags:
          only: /.*/
  - build-libqaul-linux:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /.*/
  - build-libqaul-android:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /.*/
  - build-libqaul-ios:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /.*/
  - build-libqaul-macos:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /.*/
  - build-libqaul-windows:
      requires:
        - verify-version-rust
      filters:
        tags:
          only: /.*/
  - publish-rust-github-release:
      requires:
        - build-libqaul-linux
        - build-libqaul-android
        - build-libqaul-ios
        - build-libqaul-macos
        - build-libqaul-windows
      filters:
        tags:
          only: /.*/
